security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        App\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    dsy: { password: "no-importa", roles: ["ROLE_SUPER_ADMIN"] }
        user_db:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            entry_point: "%authenticator%"
            guard:
                authenticators:
                    - "%authenticator%"
            provider: chain_provider
            logout:
                path: base_bundle_logout

    access_control:
        - { path: ^/secured/superadmin, roles: [ROLE_SUPER_ADMIN] }
        - { path: ^/secured/user, roles: [ROLE_USER] }

when@dev:
    parameters:
        authenticator: dsarhoya\BaseBundle\Security\Guard\NoPasswordLoginFormAuthenticator

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
