# Rutas públicas
home:
  path: /
  controller: App\Controller\HomeController::index
  methods: GET

app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  methods: GET

# Rutas protegidas del administrador
admin_dashboard:
  path: /admin
  controller: App\Controller\AdminController::dashboard
  methods: GET
  defaults:
    _locale: es

admin_category:
  path: /secured/user/category
  controller: App\Controller\CategoryController::index
  methods: GET

admin_news:
  path: /secured/user/news
  controller: App\Controller\NewsController::index
  methods: GET

api:
  resource: "routes/api.yaml"
  prefix: /api/1
