# Rutas públicas
home:
  path: /
  controller: App\Controller\HomeController::index
  methods: GET

app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  methods: GET
  
secured:
    resource: '../src/Controller/Secured/'
    type: annotation
    prefix: /secured

# API

api:
  resource: "routes/api.yaml"
  prefix: /api/1
